language: python

python:
  - "3.6"

services:
  - docker

script:
 - echo "skipping tests"
 
before_deploy:
    - docker run --rm --privileged multiarch/qemu-user-static:register
    - docker build -t 3dirk/z2m-nwm .
    
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
